- name: Stand up webapp container
  docker:
    name: dicetowertopten_webapp
    image: "wilsonianb/dice_tower:{{deploy_environment}}"
    email: "{{ lookup('env','DOCKER_EMAIL') }}"
    username: "{{ lookup('env','DOCKER_USERNAME') }}"
    password: "{{ lookup('env','DOCKER_PASSWORD') }}"
    state: reloaded
    pull: always
    links:
      - dicetowertopten_postgres:postgres
    restart_policy: always
    ports:
      - "1337:1337"
    expose:
      - 1337
